### ISSUE TITLE
Not a issue, just charts and a question

### ISSUE THREAD

**Issue by thomsbe** [oliverwehrens/homeassistant_ostrom_integration#1]
I found your integration of O-Strom into Home Assistant – amazing work, thank you so much for sharing it!

I wanted to express my appreciation, and also let you know that I’ve added two ApexCharts configurations for price visualization (past and future), which I’m sharing below in case they’re useful for others.

Thanks again for your contribution!

```yaml
type: custom:apexcharts-card
graph_span: 23h
span:
  start: hour
  offset: "-1h"
header:
  title: Strompreise Zukunft(€/kWh)
  show: true
apex_config:
  xaxis:
    type: datetime
    labels:
      datetimeFormatter:
        hour: HH:mm
        day: dd MMM
  plotOptions:
    bar:
      colors:
        ranges:
          - from: 0
            to: 0.15
            color: "#2ecc71"
          - from: 0.15
            to: 0.2
            color: "#a6d96a"
          - from: 0.2
            to: 0.25
            color: "#ffff99"
          - from: 0.25
            to: 0.3
            color: "#fdae61"
          - from: 0.3
            to: 0.35
            color: "#f46d43"
          - from: 0.35
            to: 1
            color: "#d73027"
series:
  - entity: sensor.ostrom_energy_spotpreis
    attribute: prices
    float_precision: 3
    type: column
    name: Preis
    data_generator: |
      const prices = entity.attributes.prices;
      return Object.entries(prices).map(([timestamp, value]) => {
        const date = new Date(timestamp);
        return [date, value];
      });
    show:
      datalabels: false
      in_header: true
yaxis:
  - min: 0
    max: 0.5
```

```yaml
type: custom:apexcharts-card
graph_span: 24h
header:
  title: Strompreise (€/kWh)
  show: true
apex_config:
  xaxis:
    type: datetime
    labels:
      datetimeFormatter:
        hour: HH:mm
        day: dd MMM
  plotOptions:
    bar:
      colors:
        ranges:
          - from: 0
            to: 0.15
            color: "#2ecc71"
          - from: 0.15
            to: 0.2
            color: "#a6d96a"
          - from: 0.2
            to: 0.25
            color: "#ffff99"
          - from: 0.25
            to: 0.3
            color: "#fdae61"
          - from: 0.3
            to: 0.35
            color: "#f46d43"
          - from: 0.35
            to: 1
            color: "#d73027"
series:
  - entity: sensor.ostrom_energy_spotpreis
    type: column
    name: Preis
    float_precision: 3
    group_by:
      duration: 1h
      func: avg
    show:
      datalabels: false
      in_header: false
yaxis:
  - min: 0
    max: 0.5
```

Looks like this:

![Image](https://github.com/user-attachments/assets/296ef75e-96ab-4d78-ad19-bb7c9b9366a1)

Do you know if the O-Strom API also provides access to a *user’s own energy consumption*? If so, that would be fantastic to integrate into Home Assistant as well.

If not, no problem, I’m fairly experienced with Python and might take a look at the API myself to see what’s possible.

Thanks again and keep up the awesome work!

**Comment by oliverwehrens** [comment]
Thanks a lot! Updated the readme with the nice charts. I will create a new issue for the consumption which seems possible.

**Comment by riqo89** [comment]
Here is another representation that combines past and future prices as well as the current electrical power (if available as an entity). Only the column thickness seems to be buggy sometimes, especially with stacked option; so try different values.

```yaml
type: custom:apexcharts-card
graph_span: 18h
stacked: true
span:
  start: hour
  offset: "-6h"
now:
  show: true
  color: orange
  label: Jetzt
apex_config:
  legend:
    show: false
  xaxis:
    type: datetime
    labels:
      datetimeFormatter:
        hour: HH:mm
        day: dd MMM
  plotOptions:
    bar:
      colors:
        ranges:
          - from: 0
            to: 0.15
            color: "#2ecc71"
          - from: 0.15
            to: 0.2
            color: "#a6d96a"
          - from: 0.2
            to: 0.25
            color: "#ffff99"
          - from: 0.25
            to: 0.3
            color: "#fdae61"
          - from: 0.3
            to: 0.35
            color: "#f46d43"
          - from: 0.35
            to: 1
            color: "#d73027"
      columnWidth: 75px
series:
  - entity: sensor.ostrom_energy_spotpreis
    yaxis_id: preis
    type: column
    name: Zuletzt
    stack_group: preise
    float_precision: 2
    group_by:
      duration: 1h
      func: avg
    show:
      datalabels: false
  - entity: sensor.ostrom_energy_spotpreis
    yaxis_id: preis
    attribute: prices
    type: column
    name: Künftig
    stack_group: preise
    float_precision: 2
    data_generator: |
      const prices = entity.attributes.prices;
      return Object.entries(prices).map(([timestamp, value]) => {
        const date = new Date(timestamp);
        return [date, value];
      });
  - entity: sensor.wattwachter_e320_power
    yaxis_id: leistung
    type: line
    name: Leistung
    float_precision: 2
    color: lightskyblue
    unit: kW
    transform: return x / 1000;
    stroke_width: 3
    extend_to: now
    group_by:
      duration: 1h
      func: avg
yaxis:
  - id: preis
    min: 0
    max: 0.4
    decimals: 2
    apex_config:
      tickAmount: 8
  - id: leistung
    opposite: true
    min: 0
    max: 16
    decimals: 1
    apex_config:
      tickAmount: 8
      reversed: true
```

<img width="662" height="485" alt="Image" src="https://github.com/user-attachments/assets/e569686d-6894-44fd-9431-3325d341448e" />
